// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7fnw6frY4Tpg_4aGvA_lQMyf9frxCUB4',
    appId: '1:10828870442:web:6f90f6ffcb2739e008e453',
    messagingSenderId: '10828870442',
    projectId: 'mesclainvest-34c45',
    authDomain: 'mesclainvest-34c45.firebaseapp.com',
    storageBucket: 'mesclainvest-34c45.firebasestorage.app',
    measurementId: 'G-P8XW64JMGT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3Gql6v5AzsYmHC8OKyMPi92ZKOiaSUTU',
    appId: '1:10828870442:android:8d6994536e5c404508e453',
    messagingSenderId: '10828870442',
    projectId: 'mesclainvest-34c45',
    storageBucket: 'mesclainvest-34c45.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMBVWbaiIMlPR3if10-rzqNRSAk6OGLno',
    appId: '1:10828870442:ios:8d0a60e675ea916b08e453',
    messagingSenderId: '10828870442',
    projectId: 'mesclainvest-34c45',
    storageBucket: 'mesclainvest-34c45.firebasestorage.app',
    iosBundleId: 'com.example.mesclaInvest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMBVWbaiIMlPR3if10-rzqNRSAk6OGLno',
    appId: '1:10828870442:ios:8d0a60e675ea916b08e453',
    messagingSenderId: '10828870442',
    projectId: 'mesclainvest-34c45',
    storageBucket: 'mesclainvest-34c45.firebasestorage.app',
    iosBundleId: 'com.example.mesclaInvest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD7fnw6frY4Tpg_4aGvA_lQMyf9frxCUB4',
    appId: '1:10828870442:web:382fc5dc48001d7508e453',
    messagingSenderId: '10828870442',
    projectId: 'mesclainvest-34c45',
    authDomain: 'mesclainvest-34c45.firebaseapp.com',
    storageBucket: 'mesclainvest-34c45.firebasestorage.app',
    measurementId: 'G-QR1BR0PX88',
  );
}
